name: Scheduled Spider

on:
  schedule:
    - cron: "15 2 * * *" 

jobs:
  run_scrapy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install Scrapy and other dependencies
      run: |
        cd vegetable_price
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scrapy Spider
      run: |
        cd vegetable_price  
        scrapy crawl nepalicalender
